import React from "react";
import NavbarSection from "components/_home/NavbarSection";
import SecondBanner from "components/_home/SecondBanner";
import Footer from "components/Footer";
import Inquery from "components/common/Modal";
const index = () => {
  return (
    <div>
      <NavbarSection />
      <SecondBanner
        mainhead="Terms and condition"
        image={"/resource/clean.jpg"}
      />
      <Inquery />
      <section className="car-coating p-0">
        <div className="container">
          <div className="row">
            <div className="mt-5" data-aos="fade-up" data-aos-delay="100">
              <h3>1. Introduction</h3>
              Welcome to shreecardetailsing. shreecardetailsing (“us”, “we”, or
              “our”) operates www.shreecardetailsing.in (hereinafter referred to
              as “Service”). Our Privacy Policy governs your visit to
              www.shreecardetailsing.in, and explains how we collect, safeguard
              and disclose information that results from your use of our
              Service. We use your data to provide and improve Service. By using
              Service, you agree to the collection and use of information in
              accordance with this policy. Unless otherwise defined in this
              Privacy Policy, the terms used in this Privacy Policy have the
              same meanings as in our Terms and Conditions. Our Terms and
              Conditions (“Terms”) govern all use of our Service and together
              with the Privacy Policy constitutes your agreement with us
              (“agreement”).
              <h3>2. Definitions</h3>
              SERVICE means the www.shreecardetailsing.in website operated by
              shreecardetailsing. PERSONAL DATA means data about a living
              individual who can be identified from those data (or from those
              and other information either in our possession or likely to come
              into our possession). USAGE DATA is data collected automatically
              either generated by the use of Service or from Service
              infrastructure itself (for example, the duration of a page visit).
              COOKIES are small files stored on your device (computer or mobile
              device). DATA CONTROLLER means a natural or legal person who
              (either alone or jointly or in common with other persons)
              determines the purposes for which and the manner in which any
              personal data are, or are to be, processed. For the purpose of
              this Privacy Policy, we are a Data Controller of your data. DATA
              PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal
              person who processes the data on behalf of the Data Controller. We
              may use the services of various Service Providers in order to
              process your data more effectively. DATA SUBJECT is any living
              individual who is the subject of Personal Data. THE USER is the
              individual using our Service. The User corresponds to the Data
              Subject, who is the subject of Personal Data.
              <h3>3. Information Collection and Use</h3>
              We collect several different types of information for various
              purposes to provide and improve our Service to you.
              <h3>4. Types of Data Collected</h3>
              <h4>4.1. Personal Data</h4>
              While using our Service, we may ask you to provide us with certain
              personally identifiable information that can be used to contact or
              identify you (“Personal Data”). Personally identifiable
              information may include, but is not limited to:
              <h6>4.1.1. Email address</h6>
              <h6>4.1.2. First name and last name</h6>
              <h6>4.1.3. Phone number</h6>
              <h6>
                4.1.4. Address, Country, State, Province, ZIP/Postal code, City
              </h6>
              <h6>4.1.5. Cookies and Usage Data</h6>
              We may use your Personal Data to contact you with newsletters,
              marketing or promotional materials and other information that may
              be of interest to you. You may opt out of receiving any, or all,
              of these communications from us by following the unsubscribe link.
              <h4>4.2. Usage Data</h4>
              We may also collect information that your browser sends whenever
              you visit our Service or when you access Service by or through any
              device (“Usage Data”). This Usage Data may include information
              such as your computer’s Internet Protocol address (e.g. IP
              address), browser type, browser version, the pages of our Service
              that you visit, the time and date of your visit, the time spent on
              those pages, unique device identifiers and other diagnostic data.
              When you access Service with a device, this Usage Data may include
              information such as the type of device you use, your device unique
              ID, the IP address of your device, your device operating system,
              the type of Internet browser you use, unique device identifiers
              and other diagnostic data.
              <h5>4.3. Tracking Cookies Data</h5>
              We use cookies and similar tracking technologies to track the
              activity on our Service and we hold certain information. Cookies
              are files with a small amount of data which may include an
              anonymous unique identifier. Cookies are sent to your browser from
              a website and stored on your device. Other tracking technologies
              are also used such as beacons, tags and scripts to collect and
              track information and to improve and analyze our Service. You can
              instruct your browser to refuse all cookies or to indicate when a
              cookie is being sent. However, if you do not accept cookies, you
              may not be able to use some portions of our Service. Examples of
              Cookies we use:
              <h6>4.3.1. Session Cookies:</h6> We use Session Cookies to operate
              our Service.
              <h3>4.3.2. Preference Cookies:</h3> We use Preference Cookies to
              remember your preferences and various settings.
              <h3>4.3.3. Security Cookies:</h3> We use Security Cookies for
              security purposes.
              <h3>4.3.4. Advertising Cookies:</h3> Advertising Cookies are used
              to serve you with advertisements that may be relevant to you and
              your interests.
              <h3>4.4. Other Data</h3>
              While using our Service, we may also collect the following
              information: sex, age, date of birth, place of birth, passport
              details, citizenship, registration at place of residence and
              actual address, telephone number (work, mobile), details of
              documents on education, qualification, professional training,
              employment agreements, NDA agreements, information on bonuses and
              compensation, information on marital status, family members,
              social security (or other taxpayer identification) number, office
              location and other data.
              <h3>5. Use of Data</h3>
              shreecardetailsing uses the collected data for various purposes:
              <h4>5.1. to provide and maintain our Service;</h4>
              <h4>5.2. to notify you about changes to our Service;</h4>
              <h4>
                5.3. to allow you to participate in interactive features of our
                Service when you choose to do so;
              </h4>
              <h4>5.4. to provide customer support;</h4>
              <h4>
                5.5. to gather analysis or valuable information so that we can
                improve our Service;
              </h4>
              <h4>5.6. to monitor the usage of our Service;</h4>
              <h4>5.7. to detect, prevent and address technical issues;</h4>
              <h4>
                5.8. to fulfil any other purpose for which you provide it;
              </h4>
              <h4>
                5.9. to carry out our obligations and enforce our rights arising
                from any contracts entered into between you and us, including
                for billing and collection;
              </h4>
              <h4>
                5.10. to provide you with notices about your account and/or
                subscription, including expiration and renewal notices,
                email-instructions, etc.;
              </h4>
              <h4>
                5.11. to provide you with news, special offers and general
                information about other goods, services and events which we
                offer that are similar to those that you have already purchased
                or enquired about unless you have opted not to receive such
                information;
              </h4>
              <h4>
                5.12. in any other way we may describe when you provide the
                information;
              </h4>
              <h4>5.13. for any other purpose with your consent.</h4>
              <h3>6. Retention of Data</h3>
              We will retain your Personal Data only for as long as is necessary
              for the purposes set out in this Privacy Policy. We will retain
              and use your Personal Data to the extent necessary to comply with
              our legal obligations (for example, if we are required to retain
              your data to comply with applicable laws), resolve disputes, and
              enforce our legal agreements and policies. We will also retain
              Usage Data for internal analysis purposes. Usage Data is generally
              retained for a shorter period, except when this data is used to
              strengthen the security or to improve the functionality of our
              Service, or we are legally obligated to retain this data for
              longer time periods.
              <h3>7. Transfer of Data</h3>
              Your information, including Personal Data, may be transferred to –
              and maintained on – computers located outside of your state,
              province, country or other governmental jurisdiction where the
              data protection laws may differ from those of your jurisdiction.
              If you are located outside India and choose to provide information
              to us, please note that we transfer the data, including Personal
              Data, to India and process it there. Your consent to this Privacy
              Policy followed by your submission of such information represents
              your agreement to that transfer. shreecardetailsing will take all
              the steps reasonably necessary to ensure that your data is treated
              securely and in accordance with this Privacy Policy and no
              transfer of your Personal Data will take place to an organisation
              or a country unless there are adequate controls in place including
              the security of your data and other personal information.
              <h3>8. Disclosure of Data</h3>
              We may disclose personal information that we collect, or you
              provide:
              <h5>8.1. Disclosure for Law Enforcement.</h5> Under certain
              circumstances, we may be required to disclose your Personal Data
              if required to do so by law or in response to valid requests by
              public authorities.
              <h5>8.2. Business Transaction.</h5> If we or our subsidiaries are
              involved in a merger, acquisition or asset sale, your Personal
              Data may be transferred.
              <h5>8.3. Other cases.</h5> We may disclose your information also:
              <h6>8.3.1. to our subsidiaries and affiliates;</h6>
              <h6>
                8.3.2. to contractors, service providers, and other third
                parties we use to support our business;
              </h6>
              <h6>8.3.3. to fulfil the purpose for which you provide it;</h6>
              <h6>
                8.3.4. for the purpose of including your company’s logo on our
                website;
              </h6>
              <h6>
                8.3.5. for any other purpose disclosed by us when you provide
                the information;
              </h6>
              <h6>8.3.6. with your consent in any other cases;</h6>
              <h6>
                8.3.7. if we believe disclosure is necessary or appropriate to
                protect the rights, property, or safety of the Company, our
                customers, or others.
              </h6>
              <h3>9. Security of Data</h3>
              The security of your data is important to us but remember that no
              method of transmission over the Internet
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
};

export default index;
